/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aoc.trebuchet;

import java.io.IOException;
import java.net.URISyntaxException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

public class App {
    public List<String> readFile() throws IOException, URISyntaxException {
        Path path = Path.of(getClass().getClassLoader().getResource("input.txt").toURI());
        return Files.readAllLines(path);
    }
    
    public int getSimpleCalibrationValue() throws IOException, URISyntaxException {
        return readFile().stream().map(this::getSimpleNumberFromLine).reduce(0, (total, next) -> total + next);
    } 

    public int getSimpleNumberFromLine(String line) {
        boolean firstFound = false, lastFound = false;
        int firstIndex = -1, lastIndex = -1;
        for (var i = 0; i < line.length(); i++) {
            if(!firstFound) {
                if(Character.isDigit(line.charAt(i))) {
                    firstFound = true;
                    firstIndex = i;
                }
            }
            if(!lastFound) {
                if(Character.isDigit(line.charAt(line.length() - i - 1))) {
                    lastFound = true;
                    lastIndex = line.length() - i -1;
                }
            }
            if(firstFound && lastFound){
                return Integer.valueOf("" + line.charAt(firstIndex) + line.charAt(lastIndex));
            }
        }  return -1;
    }

    public static void main(String[] args) {
        try {
            System.out.println("the calibration value is: "+ new App().getSimpleCalibrationValue());
        } catch (IOException | URISyntaxException e) {
            e.printStackTrace();
        }
    }
}
